### ISSUE TITLE
Total number of countries only appears when hovering a country

### ISSUE THREAD

**Issue by robinmetral** [robinmetral/footprints#9]
The total number of countries (`footprintCountries.length`) should be passed to the Leaflet control box when initializing the box, not when updating it.

**Comment by michaelymo** [comment]
I would like to work on this issue

**Comment by robinmetral** [comment]
Thank you @michaelymo, that would be great! :rocket: 

Make sure you take a look at the [contributing guide](https://github.com/robinmetral/footprints/blob/master/CONTRIBUTING.md), and let me know if you need any help :slightly_smiling_face:

**Comment by michaelymo** [comment]
Hi!
I'm suffering about the implimentation.

I have tried to pass `footprintsCountries` Object to leaflet control box when initializing the box.
like
```
info.footprintsCountries = footprintsCountries;
```
but This must still call info.update() for rerendering DOM.

Then, I have looked for something like data container property in [leaflet control documentation](https://leafletjs.com/reference.html#control).
But I could not find it.

How about this implementation instead?
```
let footprintsCountries = [];
fetch("./footprints.json")
  .then(response => {
    return response.json();
  }).then(json => {
    // make array of visited countries
    footprintsCountries.push(...json.footprints);
    // update leaflet control box // ←added
    info.update(); // ←added
    // call getGeometry function
    getGeometry(footprintsCountries);
  }).catch(err => {
    console.log("There was an error while fetching the visited countries");
  });
```

Or Could you help me?

thanks :)

**Comment by robinmetral** [comment]
I think you're right @michaelymo, we'd need to go through `info.update();` in any case. Thanks for looking up the docs!

And I like your solution of triggering a control update when the json has loaded. Clean, simple, that's what we want! :slightly_smiling_face: 

Do you want to make a PR for it? I'll merge it.

Thanks again :rocket:

**Comment by michaelymo** [comment]
Thank you for the reply and  your opinion!

Yes, I do. I'll do it now!😄
